version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["type/dependencies"]
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: "/"
    labels: ["type/dependencies"]
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

